// A2UI v0.9 prompt section: teaches the LLM to optionally emit a declarative
// UI block wrapped in <a2ui-json> tags, with OnCall-domain few-shot examples.
// The examples are generated by builders so UI structure changes only need a
// builder edit — the prompt stays in sync automatically.

export const A2UI_OPEN_TAG = "<a2ui-json>";
export const A2UI_CLOSE_TAG = "</a2ui-json>";

// Protocol constant duplicated from catalog/index.ts on purpose: the catalog
// module pulls in the whole React component tree and must stay client-only.
export const A2UI_CATALOG_ID =
  "https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json";

export const UI_ACTION_PREFIX = "[UI_ACTION]";

function buildAlertListExample(): unknown[] {
  const surfaceId = "alerts-overview-1";
  return [
    {
      version: "v0.9",
      createSurface: { surfaceId, catalogId: A2UI_CATALOG_ID },
    },
    {
      version: "v0.9",
      updateComponents: {
        surfaceId,
        components: [
          {
            id: "root",
            component: "Column",
            children: ["alerts-title", "alerts-list"],
          },
          {
            id: "alerts-title",
            component: "Text",
            variant: "h3",
            text: { path: "/title" },
          },
          {
            id: "alerts-list",
            component: "List",
            direction: "vertical",
            children: { componentId: "alert-card", path: "/alerts" },
          },
          { id: "alert-card", component: "Card", child: "alert-body" },
          {
            id: "alert-body",
            component: "Column",
            children: ["alert-head", "alert-desc", "alert-since", "alert-ack"],
          },
          {
            id: "alert-head",
            component: "Row",
            justify: "spaceBetween",
            align: "center",
            children: ["alert-name", "alert-severity"],
          },
          {
            id: "alert-name",
            component: "Text",
            variant: "h4",
            text: { path: "name" },
          },
          {
            id: "alert-severity",
            component: "Badge",
            variant: "destructive",
            text: { path: "severity" },
          },
          {
            id: "alert-desc",
            component: "Text",
            text: { path: "description" },
          },
          {
            id: "alert-since",
            component: "Text",
            variant: "caption",
            text: { path: "startsAt" },
          },
          {
            id: "alert-ack",
            component: "Button",
            variant: "primary",
            child: "alert-ack-label",
            action: {
              event: {
                name: "ack_alert",
                context: {
                  alertname: { path: "name" },
                  severity: { path: "severity" },
                },
              },
            },
          },
          { id: "alert-ack-label", component: "Text", text: "Acknowledge" },
        ],
      },
    },
    {
      version: "v0.9",
      updateDataModel: {
        surfaceId,
        path: "/",
        value: {
          title: "2 firing alerts",
          alerts: [
            {
              name: "HighErrorRate",
              severity: "critical",
              description: "Error rate above 5% on service checkout for 10m.",
              startsAt: "2026-08-17 09:12:00",
            },
            {
              name: "MySQLReplicationLag",
              severity: "warning",
              description: "Replica lag is 45s on db-order-replica-2.",
              startsAt: "2026-08-17 08:40:00",
            },
          ],
        },
      },
    },
  ];
}

function buildMetricsReportExample(): unknown[] {
  const surfaceId = "qps-report-1";
  return [
    {
      version: "v0.9",
      createSurface: { surfaceId, catalogId: A2UI_CATALOG_ID },
    },
    {
      version: "v0.9",
      updateComponents: {
        surfaceId,
        components: [
          {
            id: "root",
            component: "Column",
            children: ["report-title", "qps-chart", "qps-table"],
          },
          {
            id: "report-title",
            component: "Text",
            variant: "h3",
            text: { path: "/title" },
          },
          {
            id: "qps-chart",
            component: "Chart",
            variant: "line",
            data: { path: "/rows" },
            xKey: "time",
            series: [
              { key: "qps", label: "QPS" },
              { key: "errors", label: "Errors" },
            ],
            height: 240,
          },
          {
            id: "qps-table",
            component: "Table",
            caption: "Hourly QPS of service checkout",
            columns: [
              { key: "time", header: "Time" },
              { key: "qps", header: "QPS" },
              { key: "errors", header: "Errors" },
            ],
            rows: { path: "/rows" },
          },
        ],
      },
    },
    {
      version: "v0.9",
      updateDataModel: {
        surfaceId,
        path: "/",
        value: {
          title: "Service checkout QPS (last 3 hours)",
          rows: [
            { time: "10:00", qps: 1240, errors: 3 },
            { time: "11:00", qps: 1685, errors: 12 },
            { time: "12:00", qps: 2210, errors: 5 },
          ],
        },
      },
    },
  ];
}

function buildSilenceFormExample(): unknown[] {
  const surfaceId = "silence-form-1";
  return [
    {
      version: "v0.9",
      createSurface: { surfaceId, catalogId: A2UI_CATALOG_ID },
    },
    {
      version: "v0.9",
      updateComponents: {
        surfaceId,
        components: [
          { id: "root", component: "Card", child: "form-body" },
          {
            id: "form-body",
            component: "Column",
            children: [
              "form-title",
              "alertname-field",
              "hours-field",
              "comment-field",
              "submit-btn",
            ],
          },
          {
            id: "form-title",
            component: "Text",
            variant: "h4",
            text: "Create alert silence",
          },
          {
            id: "alertname-field",
            component: "TextField",
            label: "Alert name",
            value: { path: "/alertname" },
          },
          {
            id: "hours-field",
            component: "TextField",
            label: "Duration (hours)",
            variant: "number",
            value: { path: "/hours" },
          },
          {
            id: "comment-field",
            component: "TextField",
            label: "Comment",
            value: { path: "/comment" },
          },
          {
            id: "submit-btn",
            component: "Button",
            variant: "primary",
            child: "submit-label",
            action: {
              event: {
                name: "create_silence",
                context: {
                  alertname: { path: "/alertname" },
                  hours: { path: "/hours" },
                  comment: { path: "/comment" },
                },
              },
            },
          },
          { id: "submit-label", component: "Text", text: "Create silence" },
        ],
      },
    },
    {
      version: "v0.9",
      updateDataModel: {
        surfaceId,
        path: "/",
        value: { alertname: "HighErrorRate", hours: "2", comment: "" },
      },
    },
  ];
}

function renderExample(name: string, messages: unknown[]): string {
  return `---BEGIN ${name}---\n${A2UI_OPEN_TAG}\n${JSON.stringify(messages)}\n${A2UI_CLOSE_TAG}\n---END ${name}---`;
}

export const A2UI_PROMPT_SECTION = `## Interactive UI (A2UI v0.9)

Besides markdown you can render interactive UI surfaces with the A2UI v0.9 protocol.
- WHEN: only when the answer presents structured data — alert lists, tabular/SQL query results, metric series or trends, or a form the user should fill and confirm. For explanations, how-tos and casual conversation, answer in plain markdown WITHOUT any A2UI block.
- HOW: write a brief markdown summary first (1-3 sentences), then append exactly ONE UI block wrapped between ${A2UI_OPEN_TAG} and ${A2UI_CLOSE_TAG}. The block content is a JSON array of A2UI messages, with no prose inside the tags.
- Message order: createSurface first, then updateComponents (the "root" component first), then updateDataModel.
- Every message is {"version":"v0.9", ...} and contains exactly one of createSurface / updateComponents / updateDataModel.
- createSurface needs a surfaceId that is unique per reply (kebab-case, e.g. "alerts-overview-3") and catalogId "${A2UI_CATALOG_ID}".
- Components use the flat wire format {"id":"...","component":"Card",...props}; children are referenced by component id. Every surface must define a component with id "root".
- Data binding: {"path":"/x"} reads the surface data model (absolute path). Inside a List item template use relative paths like {"path":"name"}. List template binding: "children":{"componentId":"<template-id>","path":"/items"}.
- Buttons fire actions: "action":{"event":{"name":"<action_name>","context":{...}}} where context values are literals or {"path"} bindings (bindings also work inside list templates and carry current form values).
- Copy real data (tool results, documents) verbatim into updateDataModel — NEVER invent values. If there is no real data, do not render a surface.
- Text and data values render as PLAIN TEXT: never put markdown syntax (**bold**, *italics*, backticked code, [links]) inside component text, table cells or data model values.
- Available components:
  - Basic: Text {text, variant?: h1|h2|h3|h4|h5|caption}, Image {url}, Row {children, justify?: start|center|end|spaceBetween, align?: start|center|end}, Column {children}, List {direction?: vertical|horizontal, children}, Card {child}, Divider {}, Button {child, variant?: primary|borderless, action}, TextField {label, value, variant?: number|longText}, CheckBox {label, value}, Slider {label?, value, min?, max?}, DateTimeInput {label?, value, enableDate?, enableTime?}, Tabs, Modal, Icon, Video, AudioPlayer, ChoicePicker.
  - Extensions: Table {caption?, columns:[{key,header}], rows: array or {"path"} binding}, Chart {variant: bar|line|area|pie, data: array or {"path"} binding, xKey, series:[{key,label?}], height?}, Badge {text, variant?: default|secondary|destructive|outline}, Alert {title, description?, variant?: default|destructive}, Progress {value: 0-100, label?, showValue?}, Item {title, description?, variant?: default|outline|muted}.
- Any component may set "weight": <number> for flex sizing inside Row/Column.
- Follow-up actions: a user message starting with "${UI_ACTION_PREFIX}" reports that the user triggered an action in a previously rendered surface; it carries the action name and a JSON context including current form values. Handle it like a normal request (run tools if needed), then confirm with markdown and, when useful, a new surface with a fresh surfaceId.

### A2UI examples

${renderExample("ALERT_LIST_EXAMPLE", buildAlertListExample())}
${renderExample("METRICS_REPORT_EXAMPLE", buildMetricsReportExample())}
${renderExample("FORM_EXAMPLE", buildSilenceFormExample())}`;
